name: Viam CLI Test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      release_type:
        required: true
        type: string
        default: latest
  workflow_call:
    inputs:
      release_type:
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:
  viam-cli-test:
    runs-on: ubuntu-latest
    steps:
    - name: find out event name
      run: echo ${{ github.event_name }}
    - name: Check out code
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
      uses: actions/checkout@v3
    - name: Check out PR branch code
      # CR erodkin: shouldn't run on PR in the future! just for testing, fix before opening
      if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Python version dependencies
      run: sudo apt-get update && sudo apt-get install -y lsb-release && sudo apt-get clean all

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: cat make
      run: cat Makefile

    - name: build
      env:
        CI_RELEASE: ${{ inputs.release_type }}
      run: |
        # CR erodkin: add back `-ci` suffix!
        GOOS=linux GOARCH=amd64 make cli
        GOOS=linux GOARCH=arm64 make cli
        GOOS=darwin GOARCH=amd64 make cli
        GOOS=darwin GOARCH=arm64 make cli
        GOOS=windows GOARCH=amd64 EXE_SUFFIX=.exe make cli

    #- name: tagged alias
      #env:
         #CI_RELEASE: ${{ github.ref_name }}
      #if: inputs.release_type == 'stable'
      #run: |
        #GOOS=linux GOARCH=amd64 make cli
        #GOOS=linux GOARCH=arm64 make cli
        #GOOS=darwin GOARCH=amd64 make cli
        #GOOS=darwin GOARCH=arm64 make cli
        #GOOS=windows GOARCH=amd64 EXE_SUFFIX=.exe make cli

    #- name: Authorize GCP Upload
      #uses: google-github-actions/auth@v1.1.1
      #with:
        #credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    #- name: upload
      #uses: google-github-actions/upload-cloud-storage@v0.10.4
      #with:
        #headers: "cache-control: no-cache"
        #path: 'bin/deploy-ci'
        #glob: 'viam-cli-*'
        #destination: 'packages.viam.com/apps/viam-cli/'
        #parent: false
